# Generated by Django 5.2.2 on 2025-06-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('author', models.CharField()),
                ('isbn', models.CharField()),
                ('availble', models.BooleanField()),
            ],
            options={
                'verbose_name': 'libraryBook',
                'verbose_name_plural': 'libraryBooks',
                'ordering': ['title'],
            },
        ),
    ]
