# Generated by Django 5.2.2 on 2025-06-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarybook',
            options={'ordering': ['author']},
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='author',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='availble',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='isbn',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
